#登陆相关配置
login:
  #开放的模拟登陆api服务器地址
  api: "http://121.196.172.243:8080/wisedu-unified-login-api-v1.0/api/login" #  有条件的可以自建
#用户组配置
users:
  #单个用户配置
  - user:
      #username 学号或者工号
      username: '2019******'
      #password 密码
      password: '***************'
      #address 地址，定位信息
      address: 中国安徽省淮南市田家庵区
      #email 接受通知消息的邮箱
      email: 
      #school 学校全称
      school: 安徽理工大学
      #lon 经度
      lon: '117.029931'
      #lat 纬度
      lat: '32.555161'
      #abnormalReason 反馈信息
      abnormalReason:
      #photo 签到照片，不需要可不填，或者直接删除
      photo: 
  #多用户配置，将下面的注释去掉即可，如果有表单内容有图片，不建议使用多用户配置
#今日校园相关配置
cpdaily:
  #是否检查问题,true检查，false不检查
  check: false
  #附加信息组默认选项配置，没有可留空
  defaults:
  #附加信息组默认选项配置，按顺序，可留空
    - default:
        title: 您目前的体温是多少
        type: 2
        value: 腋下温度37.3℃以下
    - default:
        title: 有无发热、干咳等呼吸道症状
        type: 2
        value: 无
    - default:
        title: 有无呕吐、腹泻等消化道症状
        type: 2
        value: 无
    - default:
        title: 有无其他身体不适症状
        type: 2
        value: 无