#登陆相关配置
login:
  #开放的模拟登陆api服务器地址
  api: "http://121.196.172.243:8080/wisedu-unified-login-api-v1.0/api/login"
#用户组配置
users:
  #单个用户配置
  - user:
      #username 学号或者工号
      username: '2019******'
      #password 密码
      password: '*************'
      #address 地址，定位信息
      address: 中国**省**市
      #email 接受通知消息的邮箱
      email: ************@qq.com
      #lon 当前位置经度，可以访问http://zuobiao.ay800.com/s/27/index.php获取
      lon: '11*.******'
      #lat 当前位置纬度
      lat: '3*.******'
      #school 学校全称
      school: 安徽理工大学
#今日校园相关配置
cpdaily:
  #表单组默认选项配置
  defaults:
    #表单默认选项配置，按顺序，注意，只有标必填项的才处理，不会配置就执行generate.py
    - default:
        title: 今天你的所在地是？
        type: 1
        value: **省/**市/**市
    - default:
        title: 今天你的体温是多少？
        type: 2
        value: 37.2℃及以下
    - default:
        title: 今天你的身体状况是？
        type: 2
        value: 健康
    - default:
        title: 近14天你或你的共同居住人是否有疫情中、高风险区域人员接触史？
        type: 2
        value: 否
    - default:
        title: 近14天你或你的共同居住人是否和确诊、疑似病人接触过？
        type: 2
        value: 否
    - default:
        title: 近14天你或你的共同居住人是否是确诊、疑似病例？
        type: 2
        value: 否
    - default:
        title: 你或你的共同居住人目前是否被医学隔离？
        type: 2
        value: 否
    - default:
        title: 今天你当地的健康码颜色是？
        type: 2
        value: 绿色
    - default:
        title: 本人是否承诺以上所填报的全部内容均属实、准确，不存在任何隐瞒与不实的情况，更无遗漏之处
        type: 2
        value: 是